'use client';
import { useState, useEffect } from 'react';
import { useRouter } from 'next/navigation';
import Navbar from '@/components/Navbar';
import api from '@/utils/api';
import { toast } from 'react-toastify';
import { Users, UserCheck, MessageCircle, DollarSign, CheckCircle, XCircle, Eye, LogOut } from 'lucide-react';

export default function AdminPage() {
  const router = useRouter(); const [stats, setStats] = useState(null); const [travailleurs, setTravailleurs] = useState([]); const [loading, setLoading] = useState(true);
  useEffect(() => { const session=localStorage.getItem('admin_session'); if(!session){router.push('/admin/connexion');return;} try{const d=JSON.parse(session);if(!d.valide){router.push('/admin/connexion');return;}}catch(e){router.push('/admin/connexion');return;} chargerDonnees(); }, []);
  const deconnexion = () => { localStorage.removeItem('admin_session'); router.push('/admin/connexion'); };
  const chargerDonnees = async () => { try{const[s,t]=await Promise.all([api.get('/admin/stats'),api.get('/admin/travailleurs')]);setStats(s.data);setTravailleurs(t.data.travailleurs);}catch(e){toast.error('Erreur');}finally{setLoading(false);} };
  const validerTravailleur = async (id,valide) => { try{await api.put(`/admin/travailleurs/${id}/valider`,{valide});toast.success(valide?'Validé':'Invalidé');chargerDonnees();}catch(e){toast.error('Erreur');} };
  const confirmerPaiement = async (id) => { if(!confirm('Confirmer ce paiement ?'))return; try{await api.put(`/admin/paiement/${id}/confirmer`);toast.success('Paiement confirmé');chargerDonnees();}catch(e){toast.error('Erreur');} };
  if(loading||!stats) return <div className="min-h-screen"><Navbar/><div className="flex justify-center items-center h-96"><div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary-600"></div></div></div>;
  return (
    <div className="min-h-screen"><Navbar/><div className="max-w-7xl mx-auto px-4 py-8">
      <div className="flex justify-between items-center mb-8"><h1 className="text-3xl font-bold">Dashboard Administrateur</h1><button onClick={deconnexion} className="btn-secondary flex items-center gap-2"><LogOut size={18}/>Déconnexion</button></div>
      <div className="grid md:grid-cols-4 gap-6 mb-8"><div className="card"><div className="flex items-center justify-between mb-2"><Users className="text-primary-600" size={32}/><span className="text-3xl font-bold">{stats.totalUtilisateurs}</span></div><p className="text-gray-600">Utilisateurs</p></div><div className="card"><div className="flex items-center justify-between mb-2"><UserCheck className="text-green-600" size={32}/><span className="text-3xl font-bold">{stats.travailleursPayes}</span></div><p className="text-gray-600">Travailleurs payés</p></div><div className="card"><div className="flex items-center justify-between mb-2"><MessageCircle className="text-blue-600" size={32}/><span className="text-3xl font-bold">{stats.totalMessages}</span></div><p className="text-gray-600">Messages</p></div><div className="card"><div className="flex items-center justify-between mb-2"><DollarSign className="text-yellow-600" size={32}/><span className="text-3xl font-bold">{stats.revenusTotaux}</span></div><p className="text-gray-600">Revenus (F CFA)</p></div></div>
      <div className="card mb-8"><h2 className="text-xl font-bold mb-4">Répartition par métier</h2><div className="grid md:grid-cols-3 gap-4">{stats.statsParMetier.map(s=><div key={s._id} className="flex items-center justify-between p-3 bg-gray-50 rounded"><span className="capitalize font-medium">{s._id}</span><span className="bg-primary-100 text-primary-800 px-3 py-1 rounded-full font-bold">{s.count}</span></div>)}</div></div>
      <div className="card mb-8"><h2 className="text-xl font-bold mb-4">Paiements récents</h2><div className="overflow-x-auto"><table className="w-full"><thead className="bg-gray-50"><tr><th className="px-4 py-2 text-left">Travailleur</th><th className="px-4 py-2 text-left">Métier</th><th className="px-4 py-2 text-left">Montant</th><th className="px-4 py-2 text-left">Statut</th><th className="px-4 py-2 text-left">Actions</th></tr></thead><tbody>{stats.paiementsRecents.map(p=><tr key={p._id} className="border-b"><td className="px-4 py-3">{p.travailleur?.prenom} {p.travailleur?.nom}</td><td className="px-4 py-3 capitalize">{p.travailleur?.metier}</td><td className="px-4 py-3">{p.montant} F CFA</td><td className="px-4 py-3"><span className={`px-2 py-1 rounded-full text-xs font-medium ${p.statut==='succes'?'bg-green-100 text-green-800':p.statut==='en_attente'?'bg-yellow-100 text-yellow-800':'bg-red-100 text-red-800'}`}>{p.statut}</span></td><td className="px-4 py-3">{p.statut==='en_attente'&&<button onClick={()=>confirmerPaiement(p._id)} className="text-primary-600 hover:underline text-sm">Confirmer</button>}</td></tr>)}</tbody></table></div></div>
      <div className="card"><h2 className="text-xl font-bold mb-4">Gestion des travailleurs</h2><div className="space-y-3">{travailleurs.map(t=><div key={t._id} className="flex items-center justify-between p-4 bg-gray-50 rounded-lg"><div className="flex items-center"><div className="w-12 h-12 bg-primary-100 rounded-full flex items-center justify-center text-xl mr-4">👷</div><div><h3 className="font-bold">{t.prenom} {t.nom}</h3><p className="text-sm text-gray-600 capitalize">{t.metier} - {t.ville}</p></div></div><div className="flex gap-2"><button onClick={()=>router.push(`/travailleur/${t._id}`)} className="p-2 text-blue-600 hover:bg-blue-50 rounded"><Eye size={20}/></button>{t.profilValide?<button onClick={()=>validerTravailleur(t._id,false)} className="p-2 text-red-600 hover:bg-red-50 rounded"><XCircle size={20}/></button>:<button onClick={()=>validerTravailleur(t._id,true)} className="p-2 text-green-600 hover:bg-green-50 rounded"><CheckCircle size={20}/></button>}</div></div>)}</div></div>
    </div></div>
  );
    }
